services:
  db:
    container_name: postgres_amigoscode
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigoscode_db
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5442:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: