name: CI - Deploy Backend

on:
  push:
    branches:
      - cd-workflow-test
    paths:
      - src/**
      - .github/**
      - build.gradle

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: amigoscode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: amigoscode_db
        ports:
          - "5442:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Generate keys
        run: |
          pwd
          mkdir ./src/main/resources/keys
          openssl genrsa  -out ./src/main/resources/keys/keypair.pem 2048
          openssl rsa  -in keypair.pem  -pubout  -out ./src/main/resources/keys/public.pem
          openssl pkcs8  -topk8  -inform PEM  -outform PEM  -nocrypt  -in keypair.pem  -out ./src/main/resources/keys/private.pem

      - name: Build Package and Push with Gradle
        run: gradle clean build
